model:
  base_learning_rate: 2.0e-06
  target: informationSynthesis.I2Iddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 4
    concat_mode: True
    unet_config:
      target: informationSynthesis.I2Iopenaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 9
        out_channels: 3
        model_channels: 256
        context_channels: 256
        cross_attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        - 1
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 1
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
    encoder_config:
      target: informationSynthesis.I2Iopenaimodel.FeatureEncoder
      params:
        image_size: 64
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions:
          # note: this isn\t actually the resolution but
          # the downsampling factor, i.e. this corresnponds to
          # attention on spatial resolution 8,16,32, as the
          # spatial reolution of the latents is 64 for f4
          - 8
        num_res_blocks: 1
        channel_mult:
          - 1
          - 2
          - 3
          - 4
        num_heads: 8
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: ./models/first_stage_models/vq-f4/model.ckpt
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 5
    wrap: false
    train:
      target: informationSynthesis.dataset.I2IDatasetTrain
      params:
        data_root: './data/msrs/rgbs/train/'
        size: 256
    validation:
      target: informationSynthesis.dataset.I2IDatasetValidation
      params:
        data_root: './data/msrs/rgbs/val/'
        size: 256


lightning:
  callbacks:
    image_logger:
      target: train_model.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    check_val_every_n_epoch: 100
    gpus: 1,